name: Scheduled Python Script

on:
  schedule:
    - cron: '*/30 * * * *' # Changes to '0 * * * *' for every 60 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Specify your python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Script
        run: python -m app.main
